# Generated by Django 5.2.15 on 2026-09-01 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.SlugField(help_text='Identificador de la URL pública. Ej: capacitacion-2026-09-pre', max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('momento', models.CharField(choices=[('PRE', 'Pre-test'), ('POST', 'Post-test')], max_length=4)),
                ('pareja', models.CharField(blank=True, db_index=True, help_text='Mismo valor en el pre y el post que se comparan entre sí.', max_length=60)),
                ('abierta', models.BooleanField(default=True, help_text='Si está cerrada, no admite nuevos intentos.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prueba de capacitación',
                'verbose_name_plural': 'Pruebas de capacitación',
                'ordering': ['pareja', 'momento'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaPrueba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enunciado', models.TextField()),
                ('opciones', models.JSONField(default=list)),
                ('correcta', models.CharField(help_text='Clave de la opción correcta. NUNCA se envía al navegador.', max_length=4)),
                ('explicacion', models.TextField(blank=True, help_text='Se muestra al final, solo sobre las que la persona falló.')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='capacitacion.prueba')),
            ],
            options={
                'verbose_name': 'Pregunta de prueba',
                'verbose_name_plural': 'Preguntas de prueba',
                'ordering': ['prueba', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('prueba', 'orden'), name='uniq_pregunta_orden_por_prueba')],
            },
        ),
        migrations.CreateModel(
            name='IntentoPrueba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('correo_normalizado', models.CharField(db_index=True, editable=False, max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=180)),
                ('territorial', models.CharField(blank=True, max_length=120)),
                ('respuestas', models.JSONField(default=dict)),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('segundos', models.PositiveIntegerField(default=0, help_text='Cuánto tardó en resolverla.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='capacitacion.prueba')),
            ],
            options={
                'verbose_name': 'Intento de prueba',
                'verbose_name_plural': 'Intentos de prueba',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['prueba', '-creado_en'], name='capacitacio_prueba__f74a5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('prueba', 'correo_normalizado'), name='uniq_intento_por_correo_y_prueba')],
            },
        ),
    ]
