# Generated by Django 5.2 on 2026-04-21 16:56

import apps.victimas.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametricas', '0001_initial'),
        ('victimas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('CUARTO', 'Cuarto / habitación'), ('CAMBUCHE', 'Cambuche / improvisada'), ('CONTENEDOR', 'Contenedor / prefabricada'), ('OTRO', 'Otro')], max_length=15)),
                ('condicion_ocupacion', models.CharField(blank=True, choices=[('PROPIA', 'Propia — pagada'), ('PROPIA_PAGANDO', 'Propia — en proceso de pago'), ('ARRIENDO', 'Arriendo'), ('FAMILIAR', 'Familiar / cedida'), ('INVASION', 'Invasión / sin título'), ('OTRO', 'Otro')], max_length=20)),
                ('estrato', models.PositiveSmallIntegerField(default=0, help_text='0 = no aplica / sin estrato.')),
                ('numero_cuartos', models.PositiveSmallIntegerField(default=0)),
                ('numero_personas', models.PositiveSmallIntegerField(default=1, help_text='Total de personas que habitan la vivienda.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador — en proceso de captura'), ('ACTIVO', 'Activo — caracterización completa'), ('ARCHIVADO', 'Archivado')], db_index=True, default='BORRADOR', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hogares_creados', to=settings.AUTH_USER_MODEL)),
                ('jefe_hogar', models.ForeignKey(help_text='Víctima que encabeza el hogar.', on_delete=django.db.models.deletion.PROTECT, related_name='hogares_como_jefe', to='victimas.victima')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='parametricas.municipio')),
            ],
            options={
                'verbose_name': 'Hogar',
                'verbose_name_plural': 'Hogares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiembroHogar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', apps.victimas.fields.EncryptedField(blank=True, default='', help_text='Nombre del miembro si no está registrado en el RNI (cifrado).')),
                ('numero_documento', apps.victimas.fields.EncryptedField(blank=True, default='', help_text='Documento del miembro si no está en el RNI (cifrado).')),
                ('parentesco', models.CharField(choices=[('JEFE', 'Jefe/a de hogar'), ('CONYUGE', 'Cónyuge / compañero/a'), ('HIJO_A', 'Hijo/a'), ('YERNO_NUERA', 'Yerno / nuera'), ('NIETO_A', 'Nieto/a'), ('PADRE_MADRE', 'Padre / madre'), ('HERMANO_A', 'Hermano/a'), ('OTRO_PARIENTE', 'Otro pariente'), ('NO_PARIENTE', 'Sin parentesco')], max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('ND', 'No declara')], max_length=2)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del miembro (PII — no se indexa).', null=True)),
                ('tipo_persona', models.CharField(choices=[('AUTORIZADO', 'Autorizado — víctima ≥18 años incluida en RUV'), ('TUTOR', 'Tutor — responsable de víctima menor de edad'), ('CUIDADOR', 'Cuidador permanente — responsable de adulto dependiente'), ('OTRO', 'Otro integrante del hogar')], default='OTRO', help_text='Rol del miembro según §5.1.2 del manual UARIV.', max_length=15)),
                ('incluido_ruv', models.BooleanField(default=False, help_text='True si el miembro está incluido en el RUV (Registro Único de Víctimas).')),
                ('tiene_discapacidad', models.BooleanField(default=False, help_text='El miembro tiene algún tipo de discapacidad.')),
                ('tiene_enfermedad_ruinosa', models.BooleanField(default=False, help_text='El miembro tiene enfermedad ruinosa o catastrófica (Manual §5.1.2).')),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_registrados', to=settings.AUTH_USER_MODEL)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='hogares.hogar')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametricas.tipodocumento')),
                ('victima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresías_hogar', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Miembro del Hogar',
                'verbose_name_plural': 'Miembros del Hogar',
                'ordering': ['parentesco', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hogar',
            index=models.Index(fields=['estado', 'creado_por'], name='hogares_hog_estado_4826ee_idx'),
        ),
        migrations.AddIndex(
            model_name='hogar',
            index=models.Index(fields=['jefe_hogar', 'estado'], name='hogares_hog_jefe_ho_cfe936_idx'),
        ),
    ]
