# Generated by Django 5.2 on 2026-05-20 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0001_initial'),
        ('parametricas', '0001_initial'),
        ('victimas', '0002_add_catalogo_hecho_campos_caracterizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hogar',
            name='codigo_hogar',
            field=models.CharField(blank=True, default='', help_text='Código único de identificación del hogar (generado al confirmar).', max_length=30),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='fuente_origen',
            field=models.CharField(choices=[('ENCUESTADOR', 'Registrado por encuestador en campo'), ('RUV', 'Cargado desde RUV'), ('LEGADO', 'Migrado del sistema legado (IgedEncuesta)')], default='ENCUESTADOR', help_text='Origen del registro de este miembro.', max_length=15),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='tipo_inclusion',
            field=models.CharField(choices=[('RUV_CONFIRMADO', 'Confirmado en RUV — coincidencia documento'), ('NO_INCLUIDO', 'No incluido en RUV — registrado manualmente'), ('PENDIENTE_VERIFICACION', 'Pendiente de verificación en fuentes oficiales')], default='PENDIENTE_VERIFICACION', help_text='Cómo fue incorporado este miembro al hogar.', max_length=25),
        ),
        migrations.AlterField(
            model_name='miembrohogar',
            name='tipo_persona',
            field=models.CharField(choices=[('5001', 'Autorizado — víctima ≥18 años incluida en RUV'), ('5002', 'Tutor — responsable legal de víctima menor de edad'), ('5003', 'Cuidador permanente — responsable de adulto dependiente'), ('5004', 'Otro miembro del hogar')], default='5004', help_text='Rol del miembro según §5.1.2 del manual UARIV (compatible con códigos Oracle).', max_length=4),
        ),
        migrations.AddIndex(
            model_name='miembrohogar',
            index=models.Index(fields=['hogar', 'tipo_persona'], name='hogares_mie_hogar_i_53eb30_idx'),
        ),
        migrations.AddIndex(
            model_name='miembrohogar',
            index=models.Index(fields=['tipo_inclusion'], name='hogares_mie_tipo_in_a9cdb5_idx'),
        ),
    ]
