# Generated by Django 5.2 on 2026-05-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0003_autorizado_rol_es_autorizado_estado_inclusion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='miembrohogar',
            name='hogares_mie_hogar_i_53eb30_idx',
        ),
        migrations.RenameIndex(
            model_name='hogar',
            new_name='hogares_hog_autoriz_fa14da_idx',
            old_name='hogares_hog_autor_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='miembrohogar',
            new_name='hogares_mie_hogar_i_6a038f_idx',
            old_name='hogares_mie_hogar_autor_idx',
        ),
        migrations.RenameIndex(
            model_name='miembrohogar',
            new_name='hogares_mie_hogar_i_39a594_idx',
            old_name='hogares_mie_hogar_rol_idx',
        ),
        migrations.RenameIndex(
            model_name='miembrohogar',
            new_name='hogares_mie_estado__92dd6c_idx',
            old_name='hogares_mie_est_incl_idx',
        ),
        migrations.AlterField(
            model_name='miembrohogar',
            name='incluido_ruv',
            field=models.BooleanField(default=False, help_text='True si el miembro está incluido en el RUV. Sincronizado con estado_inclusion.'),
        ),
        migrations.AlterField(
            model_name='miembrohogar',
            name='tipo_persona',
            field=models.CharField(choices=[('5001', 'Autorizado — víctima ≥18 años incluida en RUV'), ('5002', 'Tutor — responsable legal de víctima menor de edad'), ('5003', 'Cuidador permanente — responsable de adulto dependiente'), ('5004', 'Otro miembro del hogar')], default='5004', help_text='Código Oracle §5.1.2 (compatibilidad legado). Se sincroniza con rol/es_autorizado.', max_length=4),
        ),
    ]
