# Generated by Django 5.2 on 2026-06-10 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0004_remove_miembrohogar_hogares_mie_hogar_i_53eb30_idx_and_more'),
        ('parametricas', '0001_initial'),
        ('victimas', '0002_add_catalogo_hecho_campos_caracterizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hogar',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ARCHIVADO'), _negated=True), fields=('autorizado',), name='uniq_hogar_no_archivado_por_autorizado'),
        ),
    ]
