# Generated by Django 5.2.15 on 2026-07-06 13:49

import apps.hogares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0005_hogar_uniq_hogar_no_archivado_por_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrohogar',
            name='constancia',
            field=models.FileField(blank=True, help_text='Documento que acredita el rol de tutor/cuidador.', null=True, upload_to=apps.hogares.models.ruta_constancia),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='constancia_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo subido (para mostrar al usuario).', max_length=255),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='constancia_subida_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que se subió la constancia.', null=True),
        ),
    ]
