# Generated by Django 5.2.15 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0006_miembrohogar_constancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrohogar',
            name='estado_inclusion',
            field=models.CharField(choices=[('INCLUIDO', 'Incluido — víctima registrada en el RUV'), ('NO_INCLUIDO', 'No incluido — no registrado en el RUV'), ('NO_VERIFICADO', 'No verificado — no está en el padrón descargado')], default='NO_INCLUIDO', help_text='Indica si la persona está registrada como víctima en el RUV.', max_length=15),
        ),
    ]
