"""
El retiro de un integrante del hogar: una novedad, no un borrado.

─── Por qué ─────────────────────────────────────────────────────────────────
Entre una caracterización y la siguiente la familia cambia: alguien muere,
alguien se va, alguien deja de convivir. Hasta hoy el sistema solo sabía BORRAR
un integrante, y solo antes de la primera caracterización completada — con razón,
porque borrar a alguien ya reportado altera un dato entregado.

El resultado era que al recaracterizar no había forma de decir que la persona ya
no pertenece al hogar. Con el control de vigencia retirado (ver
`encuestas/migrations/0010_recaracterizacionvigente.py`) la recaracterización pasó
a ser el caso corriente, y eso dejaba al encuestador sin salida frente a una
familia que sí cambió. El único mensaje disponible lo mandaba a «solicitar el
ajuste a su coordinación», que no existe como proceso.

─── Qué agrega ──────────────────────────────────────────────────────────────
Cinco campos en `MiembroHogar`. La fila NO se borra nunca: tiene que quedarse
porque las respuestas de la caracterización anterior apuntan a ella.

  retirado_en         la fecha del HECHO, informada por la familia
  motivo_retiro       falleció / cambió de residencia / ya no convive / otro
  observacion_retiro  el detalle, obligatorio cuando el motivo es «otro»
  retirado_por        quién lo registró
  retirado_at         cuándo se REGISTRÓ — distinto de cuándo ocurrió

Las dos fechas separadas son lo que permite ver un retiro informado con seis meses
de retraso. Con una sola, ese caso se vuelve invisible.

Con `retirado_en` cada entrevista puede decir quiénes eran el hogar en SU momento:
la caracterización anterior sigue siendo válida y la nueva no pregunta por quien
ya no está.

─── Esta migración no cambia el comportamiento de nada ──────────────────────
Agrega columnas nulas y un índice. Todas las filas existentes quedan con
`retirado_en = NULL`, que significa «sigue perteneciendo al hogar» — que es
exactamente lo que hoy afirma cada una de ellas.
"""

# Generated by Django 5.2.15 on 2026-09-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0007_alter_miembrohogar_estado_inclusion'),
        ('parametricas', '0003_alter_puntoatencion_codigo'),
        ('victimas', '0021_limpiar_estado_ruv_no_verificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrohogar',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('FALLECIMIENTO', 'Falleció'), ('CAMBIO_RESIDENCIA', 'Cambió de residencia'), ('NO_CONVIVE', 'Ya no convive con el hogar'), ('OTRO', 'Otro motivo')], default='', help_text='Por qué dejó de pertenecer al hogar.', max_length=20),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='observacion_retiro',
            field=models.TextField(blank=True, default='', help_text='Detalle del retiro, escrito por el encuestador.'),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='retirado_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que el sistema registró el retiro.', null=True),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='retirado_en',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha desde la cual la persona ya no pertenece al hogar. Vacío = sigue perteneciendo.', null=True),
        ),
        migrations.AddField(
            model_name='miembrohogar',
            name='retirado_por',
            field=models.ForeignKey(blank=True, help_text='Quién registró el retiro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_retirados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='miembrohogar',
            index=models.Index(fields=['hogar', 'retirado_en'], name='miembro_hogar_retiro_idx'),
        ),
    ]
