# Generated by Django 5.2.15 on 2026-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0008_miembrohogar_motivo_retiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='codigo_hogar',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del hogar: código del encuestador + consecutivo (se genera al crear).', max_length=30),
        ),
    ]
