# Generated by Django 5.2 on 2026-04-21 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Ej: V8, V8.1, V9', max_length=20)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('fuente_documental', models.CharField(blank=True, help_text='Ej: Manual UARIV 520.06.06-1 v01, 07/10/2021', max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versión del Instrumento',
                'verbose_name_plural': 'Versiones del Instrumento',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='A, B, C, D, E, F, G', max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveSmallIntegerField()),
                ('objetivo', models.TextField(blank=True)),
                ('poblacion_objetivo', models.CharField(choices=[('AUTORIZADO', 'Solo autorizado'), ('AUTORIZADO_TUTOR_CUIDADOR', 'Autorizado/Tutor/Cuidador'), ('TODOS_MIEMBROS', 'Todos los miembros del hogar'), ('VICTIMAS_RUV', 'Solo víctimas incluidas en RUV'), ('VICTIMAS_RUV_3_ANOS_MAS', 'Víctimas RUV de 3 años o más')], default='TODOS_MIEMBROS', max_length=50)),
                ('aplicabilidad', models.JSONField(blank=True, default=dict, help_text="Reglas declarativas: {'ruv_incluido': True, 'edad_min': 3}")),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='formulario.instrumentoversion')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['orden'],
                'unique_together': {('instrumento', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='instrumentoversion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='formulario.perfil'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_externo', models.CharField(db_index=True, help_text='Código del Diccionario V8, ej: C1_tel, B9_tel', max_length=30)),
                ('codigo_diagrama', models.CharField(blank=True, help_text='Código en el diagrama de flujo del manual PDF, ej: C1, B9', max_length=10)),
                ('variable_bd', models.CharField(help_text='Nombre de columna en reportes/VIVANTO export', max_length=50)),
                ('texto', models.TextField(help_text='Pregunta literal mostrada al entrevistado')),
                ('descripcion_ayuda', models.TextField(blank=True, help_text='Conceptos y notas del manual PDF para el encuestador')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto libre'), ('TEXTO_LARGO', 'Texto largo (observaciones)'), ('NUMERICO', 'Numérico'), ('FECHA', 'Fecha'), ('BOOLEAN', 'Sí / No'), ('RADIO', 'Selección única (radio)'), ('LISTA', 'Lista desplegable'), ('LISTA_MULTIPLE', 'Selección múltiple'), ('COMBO_DINAMICO', 'Combo dinámico (DIVIPOLA, etc.)')], max_length=20)),
                ('nivel', models.CharField(choices=[('HOGAR', 'Aplica al hogar'), ('PERSONA', 'Aplica a cada miembro')], max_length=10)),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField()),
                ('validaciones', models.JSONField(blank=True, default=dict, help_text="{'min':0,'max':7} | {'regex':'^[0-9]{10}$'} | {'max_length':500}")),
                ('activa', models.BooleanField(default=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formulario.capitulo')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(help_text='Valor almacenado en la respuesta', max_length=100)),
                ('etiqueta', models.CharField(help_text='Texto visible al usuario', max_length=500)),
                ('id_resp_vivanto', models.IntegerField(blank=True, db_index=True, help_text='ID_RESP del Diccionario V8 para export a VIVANTO legacy', null=True)),
                ('orden', models.PositiveSmallIntegerField()),
                ('finaliza_capitulo', models.BooleanField(default=False, help_text='Equivale a RESFINALIZA del APK: cierra el capítulo al seleccionar')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='formulario.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaSkipLogic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expresion_origen', models.TextField(blank=True, help_text='Expresión evaluada contra contexto del hogar/persona. Ej: \'sexo == "Hombre" and 18 <= edad <= 49\'')),
                ('valor_trigger', models.CharField(blank=True, help_text='Valor que debe tomar pregunta_origen para activar la regla', max_length=100)),
                ('accion', models.CharField(choices=[('HABILITAR', 'Habilitar pregunta/capítulo'), ('DESHABILITAR', 'Deshabilitar pregunta/capítulo'), ('OBLIGAR', 'Hacer obligatoria'), ('FINALIZAR', 'Finalizar capítulo')], max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text="Referencia al manual PDF, ej: 'Manual §6.1 — Cap D solo RUV ≥3 años'", max_length=300)),
                ('capitulo_afectado', models.ForeignKey(blank=True, help_text='Si la regla afecta a un capítulo completo (ej. habilitar cap D/E)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_aplicables', to='formulario.capitulo')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='formulario.instrumentoversion')),
                ('pregunta_afectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_entrantes', to='formulario.pregunta')),
                ('pregunta_origen', models.ForeignKey(blank=True, help_text='Pregunta cuya respuesta dispara la regla. Null si la regla depende de expresión de contexto (ej. edad, inclusión RUV)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_salientes', to='formulario.pregunta')),
            ],
            options={
                'verbose_name': 'Regla Skip Logic',
                'verbose_name_plural': 'Reglas Skip Logic',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='instrumentoversion',
            unique_together={('perfil', 'numero')},
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['codigo_externo'], name='formulario__codigo__cd7ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['capitulo', 'orden'], name='formulario__capitul_c24387_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('capitulo', 'codigo_externo')},
        ),
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together={('pregunta', 'valor')},
        ),
    ]
