# Generated by Django 5.2 on 2026-04-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('vigente', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='formulario.instrumento')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['orden'],
                'unique_together': {('instrumento', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('texto', models.TextField()),
                ('texto_ayuda', models.TextField(blank=True)),
                ('tipo_respuesta', models.CharField(choices=[('TEXTO', 'Texto libre'), ('NUMERICO', 'Numérico'), ('FECHA', 'Fecha'), ('OPCION_UNICA', 'Selección única'), ('OPCION_MULTIPLE', 'Selección múltiple'), ('SINO', 'Sí / No'), ('TABLA', 'Tabla dinámica'), ('CALCULO', 'Campo calculado')], default='OPCION_UNICA', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('requerida', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('columna_padre', models.CharField(blank=True, max_length=50)),
                ('validacion', models.JSONField(blank=True, default=dict)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formulario.tema')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
                'unique_together': {('tema', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='formulario.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaDerivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(choices=[('EQ', 'Igual a'), ('NEQ', 'Diferente de'), ('GT', 'Mayor que'), ('GTE', 'Mayor o igual'), ('LT', 'Menor que'), ('LTE', 'Menor o igual'), ('IN', 'Está en'), ('NOTNULL', 'Tiene respuesta')], default='EQ', max_length=10)),
                ('valor_condicion', models.CharField(blank=True, max_length=200)),
                ('pregunta_hija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_como_hija', to='formulario.pregunta')),
                ('pregunta_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_como_padre', to='formulario.pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta Derivada',
                'verbose_name_plural': 'Preguntas Derivadas',
                'unique_together': {('pregunta_padre', 'pregunta_hija', 'valor_condicion')},
            },
        ),
    ]
