# Generated by Django 5.2 on 2026-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='codigo_diagrama',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='nivel',
            field=models.CharField(choices=[('HOGAR', 'Aplica al hogar'), ('PERSONA', 'Aplica a cada miembro')], default='HOGAR', help_text='HOGAR: se responde una vez por hogar. PERSONA: una vez por cada miembro.', max_length=10),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_precargada',
            field=models.BooleanField(default=False, help_text='True si el dato viene precargado del RUV — no editable por el encuestador'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fuente_precarga',
            field=models.CharField(blank=True, help_text='RUV | DIVIPOLA | TABLA_USUARIOS | TABLA_CONFORMACION_HOGAR', max_length=60),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_preg',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID_PREG del diccionario UARIV — para export a sistema VIVANTO', null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='no_pregunta',
            field=models.CharField(blank=True, db_index=True, help_text="Número en diagrama de flujo: A1, A2, B1, C1, J1... (columna 'No. PREGUNTA VARIABLE')", max_length=10),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='codigo',
            field=models.CharField(help_text='A, B, C, D, E, F, G, M, T', max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='codigo_externo',
            field=models.CharField(db_index=True, help_text='Variable BD del diccionario oficial: DT_ATENCION, C1_tel, Z3, PL1...', max_length=40),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('HOGAR', 'Aplica al hogar'), ('PERSONA', 'Aplica a cada miembro')], help_text='Heredado del capítulo. Se guarda aquí para queries directas sin JOIN.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='variable_bd',
            field=models.CharField(help_text='Nombre de columna en reportes/VIVANTO export (mismo que codigo_externo sin sufijo _tel)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['no_pregunta'], name='formulario__no_preg_f15763_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['id_preg'], name='formulario__id_preg_eaf5b6_idx'),
        ),
    ]
