# Generated by Django 5.2 on 2026-05-20 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_add_nivel_capitulo_y_campos_pregunta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentoversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instrumentoversion',
            name='perfil',
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.CharField(help_text='Ej: V7, V8, V8.1, V9', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('fuente_documental', models.CharField(blank=True, help_text='Ej: Manual UARIV 520.06.06-1 v01, 07/10/2021', max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['codigo', '-vigente_desde'],
                'unique_together': {('codigo', 'version')},
            },
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='formulario.instrumento'),
        ),
        migrations.AlterField(
            model_name='reglaskiplogic',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='formulario.instrumento'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
