# Generated by Django 5.2 on 2026-05-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_alter_sesionencuesta_instrumento_and_more'),
        ('formulario', '0003_alter_instrumentoversion_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentoVersion',
        ),
    ]
