# Generated by Django 5.2 on 2026-04-13 20:05

import apps.victimas.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametricas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_documento', apps.victimas.fields.EncryptedField()),
                ('numero_documento_hash', models.CharField(db_index=True, max_length=64)),
                ('primer_nombre', apps.victimas.fields.EncryptedField()),
                ('segundo_nombre', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('primer_apellido', apps.victimas.fields.EncryptedField()),
                ('segundo_apellido', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('fecha_nacimiento', apps.victimas.fields.EncryptedField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('ND', 'No declara')], db_index=True, max_length=2)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('UNION_LIBRE', 'Unión libre'), ('SEPARADO', 'Separado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=15)),
                ('pertenencia_etnica', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('INDIGENA', 'Indígena'), ('AFROCOLOMBIANO', 'Afrocolombiano / Afrodescendiente'), ('ROM', 'Pueblo Rom / Gitano'), ('RAIZAL', 'Raizal del Archipiélago'), ('PALENQUERO', 'Palenquero de San Basilio')], db_index=True, default='NINGUNA', max_length=20)),
                ('pueblo_indigena', models.CharField(blank=True, max_length=150)),
                ('discapacidad', models.BooleanField(db_index=True, default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100)),
                ('estado_ruv', models.CharField(choices=[('INCLUIDO', 'Incluido en RUV'), ('NO_INCLUIDO', 'No incluido en RUV'), ('EN_PROCESO', 'En proceso de valoración'), ('EXCLUIDO', 'Excluido del RUV')], db_index=True, default='EN_PROCESO', max_length=15)),
                ('hechos_victimizantes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victimas_registradas', to=settings.AUTH_USER_MODEL)),
                ('municipio_residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victimas_residentes', to='parametricas.municipio')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victimas', to='parametricas.tipodocumento')),
            ],
            options={
                'verbose_name': 'Víctima',
                'verbose_name_plural': 'Víctimas',
                'indexes': [models.Index(fields=['numero_documento_hash', 'tipo_documento'], name='victimas_vi_numero__444a91_idx'), models.Index(fields=['estado_ruv', 'pertenencia_etnica'], name='victimas_vi_estado__5638c8_idx')],
            },
        ),
    ]
