# Generated by Django 5.2 on 2026-05-20 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0001_initial'),
        ('victimas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoHechoVictimizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catálogo Hecho Victimizante',
                'verbose_name_plural': 'Catálogo Hechos Victimizantes',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='HechoVictima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hecho', models.DateField(blank=True, help_text='Fecha en que ocurrió el hecho victimizante.', null=True)),
                ('fuente', models.CharField(choices=[('RUV', 'Registro Único de Víctimas'), ('DECLARACION', 'Declaración ante Ministerio Público'), ('SNARIV', 'Reporte SNARIV'), ('MANUAL', 'Registro manual por funcionario')], default='RUV', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hecho Victimizante',
                'verbose_name_plural': 'Hechos Victimizantes',
                'ordering': ['fecha_hecho', 'hecho'],
            },
        ),
        migrations.RemoveField(
            model_name='victima',
            name='hechos_victimizantes',
        ),
        migrations.AddField(
            model_name='victima',
            name='cons_persona',
            field=models.IntegerField(blank=True, db_index=True, help_text='CONSUSUARIOID del sistema Oracle legado (IgedEncuesta).', null=True),
        ),
        migrations.AddField(
            model_name='victima',
            name='estado_valoracion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de valoración'), ('EN_REVISION', 'En revisión'), ('VALORADO', 'Valorado — incluido'), ('RECHAZADO', 'Valoración rechazada')], db_index=True, default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='victima',
            name='fecha_ult_caracterizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de la última sesión de caracterización completada.', null=True),
        ),
        migrations.AddField(
            model_name='victima',
            name='fuente_origen',
            field=models.CharField(choices=[('RUV', 'Registro Único de Víctimas'), ('SNARIV', 'SNARIV — sistema interinstitucional'), ('LEGADO', 'Migración del sistema legado (IgedEncuesta)'), ('MANUAL', 'Registro manual por funcionario')], db_index=True, default='RUV', max_length=10),
        ),
        migrations.AddField(
            model_name='victima',
            name='habilitado_para_caracterizacion',
            field=models.BooleanField(db_index=True, default=True, help_text='False si la víctima está excluida, fallecida o con restricción administrativa.'),
        ),
        migrations.AddIndex(
            model_name='victima',
            index=models.Index(fields=['habilitado_para_caracterizacion', 'estado_ruv'], name='victimas_vi_habilit_e2fe44_idx'),
        ),
        migrations.AddField(
            model_name='hechovictima',
            name='hecho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victimas_afectadas', to='victimas.catalogohechovictimizante'),
        ),
        migrations.AddField(
            model_name='hechovictima',
            name='lugar_hecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_ocurridos', to='parametricas.municipio'),
        ),
        migrations.AddField(
            model_name='hechovictima',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos_victimizantes', to='victimas.victima'),
        ),
        migrations.AddIndex(
            model_name='hechovictima',
            index=models.Index(fields=['victima', 'hecho'], name='victimas_he_victima_9e8339_idx'),
        ),
    ]
