# Generated by Django 5.2 on 2026-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0002_add_catalogo_hecho_campos_caracterizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='fuente_origen',
            field=models.CharField(choices=[('RUV', 'Registro Único de Víctimas'), ('SNARIV', 'SNARIV — sistema interinstitucional'), ('LEGADO', 'Migración del sistema legado (IgedEncuesta)'), ('MANUAL', 'Registro manual por funcionario'), ('REGISTRADURIA', 'Registraduría Nacional del Estado Civil')], db_index=True, default='RUV', max_length=20),
        ),
    ]
