# Generated by Django 5.2.15 on 2026-07-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0003_alter_puntoatencion_codigo'),
        ('victimas', '0005_victima_numero_documento_hash_sin_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victimas', to='parametricas.tipodocumento'),
        ),
    ]
