# Generated by Django 5.2.15 on 2026-07-30 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0006_alter_victima_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaPadron',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('SIMULADA', 'Simulada (dry-run, no escribió)')], default='EN_CURSO', max_length=12)),
                ('origen', models.CharField(blank=True, help_text='DSN y tablas de las que se leyó (sin credenciales).', max_length=200)),
                ('leidas', models.PositiveIntegerField(default=0)),
                ('creadas', models.PositiveIntegerField(default=0)),
                ('actualizadas', models.PositiveIntegerField(default=0)),
                ('descartadas', models.PositiveIntegerField(default=0)),
                ('sin_tipo_documento', models.PositiveIntegerField(default=0, help_text='Personas cargadas sin tipo de documento (la fuente no lo trae). Se encuentran por el índice de respaldo.')),
                ('motivos_descarte', models.JSONField(blank=True, default=dict, help_text='{motivo: cuántas}. Agregado, sin datos de personas.')),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Carga de padrón',
                'verbose_name_plural': 'Cargas de padrón',
                'ordering': ['-iniciada_en'],
            },
        ),
    ]
