# Generated by Django 5.2.15 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0007_cargapadron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='estado_ruv',
            field=models.CharField(choices=[('INCLUIDO', 'Incluido en RUV'), ('NO_INCLUIDO', 'No incluido en RUV'), ('EN_PROCESO', 'En proceso de valoración'), ('EXCLUIDO', 'Excluido del RUV'), ('NO_VERIFICADO', 'No verificado — no está en el padrón descargado')], db_index=True, default='EN_PROCESO', max_length=15),
        ),
    ]
