# Generated by Django 5.2.15 on 2026-08-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0009_normalizar_altas_manuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColisionDocumento',
            fields=[
                ('doc_hash', models.CharField(help_text='SHA-256 canónico de (tipo, número) — la misma llave que usa la búsqueda.', max_length=64, primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('DUPLICADO_FUENTE', 'Una sola persona, repetida en la fuente'), ('VARIANTE_NOMBRE', 'Una sola persona, con el nombre o la fecha mal escritos'), ('AMBIGUO', 'Personas distintas que comparten el documento'), ('NO_IDENTIFICANTE', 'Valor de relleno: no identifica a nadie')], db_index=True, max_length=20)),
                ('filas', models.PositiveIntegerField(help_text='Cuántas filas de Victima comparten este documento.')),
                ('personas', models.PositiveIntegerField(help_text='Cuántas personas distintas se reconocieron entre esas filas. 1 = duplicado; >1 = ambiguo; 0 = no identificante.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('victima_preferida', models.ForeignKey(blank=True, help_text='Cuando es una sola persona: la fila más completa, la que se muestra y la que va al padrón offline (survivorship). Null si es ambiguo — ahí no elegimos nosotros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Colisión de documento',
                'verbose_name_plural': 'Colisiones de documento',
                'indexes': [models.Index(fields=['clase', 'personas'], name='victimas_co_clase_4e2fe3_idx')],
            },
        ),
    ]
