# Generated by Django 5.2.15 on 2026-08-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0010_colisiondocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaAguaLegacy',
            fields=[
                ('recurso', models.CharField(choices=[('personas', 'Personas nuevas (GIC_PERSONA, por PER_IDPERSONA)'), ('hogares', 'Hogares caracterizados (GIC_HOGAR, por USU_FECHACREACION)')], max_length=20, primary_key=True, serialize=False)),
                ('ultimo_id', models.BigIntegerField(blank=True, help_text='Mayor identificador ya procesado. La próxima corrida pide > este.', null=True)),
                ('ultima_fecha', models.DateTimeField(blank=True, help_text='Instante hasta el que se leyó. La próxima corrida pide >= este menos el solape (ver SOLAPE_MINUTOS en el comando).', null=True)),
                ('corridas', models.PositiveIntegerField(default=0)),
                ('filas_ultima_corrida', models.PositiveIntegerField(default=0)),
                ('segundos_ultima_corrida', models.FloatField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca de agua del legacy',
                'verbose_name_plural': 'Marcas de agua del legacy',
            },
        ),
    ]
