# Generated by Django 5.2.15 on 2026-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0003_alter_puntoatencion_codigo'),
        ('victimas', '0011_marcaagualegacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechovictima',
            name='id_origen',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador del hecho en la fuente. Para RUV es `TBSINIESTROS_PERSONA.ID`. Permite volver a sincronizar sin duplicar y poder rastrear cada fila hasta su origen.', max_length=40, verbose_name='id en el sistema de origen'),
        ),
        migrations.AddConstraint(
            model_name='hechovictima',
            constraint=models.UniqueConstraint(condition=models.Q(('id_origen__gt', '')), fields=('fuente', 'id_origen'), name='hecho_unico_por_origen'),
        ),
    ]
