# Generated by Django 5.2.15 on 2026-08-05 15:34

import apps.victimas.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0012_hechovictima_id_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescarteUniverso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corte', models.CharField(db_index=True, max_length=40)),
                ('cons_persona_universo', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('numero_documento_hash_sin_tipo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('motivo', models.CharField(choices=[('SIN_DOCUMENTO', 'Sin documento usable (menos de 5 caracteres)'), ('DOCUMENTO_REPETIDO', 'Otra fila del mismo corte ya tomó ese documento'), ('SIN_CONS_PERSONA', 'Sin identificador en la fuente'), ('OTRO', 'Otro — ver detalle')], db_index=True, max_length=20)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Descarte del universo',
                'verbose_name_plural': 'Descartes del universo',
                'indexes': [models.Index(fields=['corte', 'motivo'], name='victimas_de_corte_e2d8d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonaUniverso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cons_persona_universo', models.BigIntegerField(db_index=True, help_text='Identificador en la fuente. NO es el cons_persona del legacy.', verbose_name='CONS_PERSONA del universo')),
                ('tipo_documento', models.CharField(blank=True, default='', help_text='TIPO_DOC tal como viene de la fuente, sin homologar.', max_length=10)),
                ('numero_documento', apps.victimas.fields.EncryptedField()),
                ('numero_documento_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('numero_documento_hash_sin_tipo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('primer_nombre', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('segundo_nombre', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('primer_apellido', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('segundo_apellido', apps.victimas.fields.EncryptedField(blank=True, default='')),
                ('genero', models.CharField(blank=True, default='', max_length=20)),
                ('pertenencia_etnica', models.CharField(blank=True, default='', max_length=60)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, default='', max_length=20)),
                ('ciclo_vital', models.CharField(blank=True, default='', max_length=20)),
                ('num_hechos', models.IntegerField(blank=True, null=True)),
                ('corte', models.CharField(db_index=True, max_length=40)),
                ('fecha_corte', models.DateField(blank=True, help_text='Primer día del mes del corte (010726 → 2026-07-01).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('victima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_universo', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Persona del universo',
                'verbose_name_plural': 'Personas del universo',
                'indexes': [models.Index(fields=['numero_documento_hash_sin_tipo', 'corte'], name='victimas_pe_numero__fa6b43_idx')],
                'constraints': [models.UniqueConstraint(fields=('corte', 'cons_persona_universo'), name='persona_universo_unica_por_corte')],
            },
        ),
    ]
