# Generated by Django 5.2.15 on 2026-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0013_descarteuniverso_personauniverso'),
    ]

    operations = [
        migrations.AddField(
            model_name='personauniverso',
            name='es_preferida',
            field=models.BooleanField(db_index=True, default=True, help_text='False = otra fila del mismo corte ganó ese documento.'),
        ),
    ]
