# Generated by Django 5.2.15 on 2026-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0014_personauniverso_es_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarteuniverso',
            name='motivo',
            field=models.CharField(choices=[('SIN_DOCUMENTO', 'Sin documento usable (menos de 5 caracteres)'), ('DOCUMENTO_REPETIDO', 'Otra fila del mismo corte ya tomó ese documento'), ('SIN_CONS_PERSONA', 'Sin identificador en la fuente'), ('ENLACE_AMBIGUO', 'El documento resuelve a más de una víctima'), ('OTRO', 'Otro — ver detalle')], db_index=True, max_length=20),
        ),
    ]
