# Generated by Django 5.2.15 on 2026-08-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0015_alter_descarteuniverso_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personauniverso',
            name='corte',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personauniverso',
            name='numero_documento_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='personauniverso',
            name='numero_documento_hash_sin_tipo',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
