# Generated by Django 5.2.15 on 2026-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0016_podar_indices_universo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personauniverso',
            name='fecha_ult_caracterizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personauniverso',
            name='vigencia_verificada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
