# Generated by Django 5.2.15 on 2026-08-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0017_universo_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='personauniverso',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
