# Generated by Django 5.2.15 on 2026-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0018_universo_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='fuente_origen',
            field=models.CharField(choices=[('RUV', 'Registro Único de Víctimas'), ('SNARIV', 'SNARIV — sistema interinstitucional'), ('LEGADO', 'Migración del sistema legado (IgedEncuesta)'), ('MANUAL', 'Registro manual por funcionario'), ('REGISTRADURIA', 'Registraduría Nacional del Estado Civil'), ('UNIVERSO_RUV', 'Universo del RUV — víctima aún sin caracterizar')], db_index=True, default='RUV', max_length=20),
        ),
    ]
