# Generated by Django 5.2.15 on 2026-07-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hogares', '0006_miembrohogar_constancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEscrituraOracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('HOGAR', 'Alta de hogar (GIC_INSERT_HOGAR1)'), ('PERSONA', 'Alta de persona (GIC_INSERT_PERSONAS)'), ('MIEMBRO', 'Vínculo miembro↔hogar (GIC_INSERT_MIEMBRO_HOGAR)'), ('TERRITORIO', 'Cascada territorial (GIC_SP_*)'), ('RESPUESTA', 'Respuesta de encuesta (SP_SET_RESPUESTAS_DE_ENCUESTA)'), ('CIERRE', 'Cierre de encuesta (CERRAR_ENCUESTA)')], max_length=20)),
                ('origen_id', models.CharField(help_text='PK interna SICAV de la entidad de este paso (no PII).', max_length=64)),
                ('destino_hog_codigo', models.CharField(blank=True, help_text='HOG_CODIGO devuelto/confirmado en Oracle (no es PII).', max_length=200)),
                ('destino_per_idpersona', models.BigIntegerField(blank=True, help_text='PER_IDPERSONA (VALSECUENCIA) devuelto por GIC_INSERT_PERSONAS.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (aún no ejecutado)'), ('DRY_RUN', 'Simulado (DRY-RUN, bloque PL/SQL registrado, sin ejecutar)'), ('EJECUTADO_SIN_VERIFICAR', 'Procedure llamado, falta confirmar por consulta'), ('VERIFICADO', 'Confirmado por SELECT en Oracle'), ('FALLIDO', 'La verificación por consulta NO encontró el resultado esperado')], default='PENDIENTE', max_length=24)),
                ('intento', models.PositiveIntegerField(default=0)),
                ('bloque_plsql', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('destino_entorno', models.CharField(blank=True, max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('hogar', models.ForeignKey(help_text='Hogar SICAV que ancla toda la máquina de estados de esta caracterización.', on_delete=django.db.models.deletion.PROTECT, related_name='registros_escritura_oracle', to='hogares.hogar')),
            ],
            options={
                'verbose_name': 'Registro de escritura a Oracle',
                'verbose_name_plural': 'Registros de escritura a Oracle',
                'ordering': ['hogar', 'creado_en'],
                'indexes': [models.Index(fields=['hogar', 'paso'], name='sincronizac_hogar_i_ca010a_idx'), models.Index(fields=['estado'], name='sincronizac_estado_1cb2c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('hogar', 'paso', 'origen_id'), name='uniq_registro_escritura_oracle_paso_origen')],
            },
        ),
    ]
