# Generated by Django 5.2.15 on 2026-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0006_miembrohogar_constancia_and_more'),
        ('sincronizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroescrituraoracle',
            name='uniq_registro_escritura_oracle_paso_origen',
        ),
        migrations.AddConstraint(
            model_name='registroescrituraoracle',
            constraint=models.UniqueConstraint(fields=('hogar', 'paso', 'origen_id', 'destino_entorno'), name='uniq_registro_escritura_oracle_paso_origen_destino'),
        ),
    ]
