# Generated by Django 5.2.15 on 2026-08-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0002_remove_registroescrituraoracle_uniq_registro_escritura_oracle_paso_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroescrituraoracle',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente (aún no ejecutado)'), ('OMITIDO', 'Omitido — su destino en el legacy es otro'), ('DRY_RUN', 'Simulado (DRY-RUN, bloque PL/SQL registrado, sin ejecutar)'), ('EJECUTADO_SIN_VERIFICAR', 'Procedure llamado, falta confirmar por consulta'), ('VERIFICADO', 'Confirmado por SELECT en Oracle'), ('FALLIDO', 'La verificación por consulta NO encontró el resultado esperado')], default='PENDIENTE', max_length=24),
        ),
    ]
