# Generated by Django 5.2.15 on 2026-08-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0003_alter_registroescrituraoracle_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroescrituraoracle',
            name='paso',
            field=models.CharField(choices=[('HOGAR', 'Alta de hogar (GIC_INSERT_HOGAR1)'), ('PERSONA', 'Alta de persona (GIC_INSERT_PERSONAS)'), ('MIEMBRO', 'Vínculo miembro↔hogar (GIC_INSERT_MIEMBRO_HOGAR)'), ('TERRITORIO', 'Cascada territorial (GIC_SP_*)'), ('RESPUESTA', 'Respuesta de encuesta (SP_SET_RESPUESTAS_DE_ENCUESTA)'), ('CAPITULO', 'Capítulo finalizado (SP_FINALIZARCAPITULO)'), ('CIERRE', "Cierre de encuesta (SP_ACTUALIZAR_ESTADO_ENCUESTA '4')")], max_length=20),
        ),
    ]
