# Generated by Django 5.2.15 on 2026-08-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0004_alter_registroescrituraoracle_paso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroescrituraoracle',
            name='paso',
            field=models.CharField(choices=[('HOGAR', 'Alta de hogar (GIC_INSERT_HOGAR1)'), ('PERSONA', 'Alta de persona (GIC_INSERT_PERSONAS)'), ('MIEMBRO', 'Vínculo miembro↔hogar (GIC_INSERT_MIEMBRO_HOGAR)'), ('VALIDADOR', 'Validadores de la persona (GIC_INSERT_VALIDADOR_HOGAR + _PARENT)'), ('HECHO', 'Hecho victimizante (GIC_INSERT_VALIDADOR_HECHO_AUX)'), ('ENCUESTADO', 'Marca de encuestado (GIC_ACTUALIZA_ENCUESTADO)'), ('TERRITORIO', 'Cascada territorial (GIC_SP_*)'), ('RESPUESTA', 'Respuesta de encuesta (SP_SET_RESPUESTAS_DE_ENCUESTA)'), ('CAPITULO', 'Capítulo finalizado (SP_FINALIZARCAPITULO)'), ('CIERRE', "Cierre de encuesta (SP_ACTUALIZAR_ESTADO_ENCUESTA '4')")], max_length=20),
        ),
    ]
