# Generated by Django 5.2.15 on 2026-08-03 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0005_alter_registroescrituraoracle_paso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLegacy',
            fields=[
                ('usu_idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usu_usuario', models.CharField(db_index=True, max_length=100)),
                ('nombre_completo', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('ent_identidad', models.BigIntegerField(blank=True, help_text='ENT_IDENTIDAD — entidad a la que pertenece.', null=True)),
                ('est_idestado', models.BigIntegerField(blank=True, help_text='EST_IDESTADO — estado en el legacy.', null=True)),
                ('codigo', models.CharField(blank=True, help_text='USU_CODIGO.', max_length=50)),
                ('dado_de_baja', models.BooleanField(default=False, help_text='USU_DADODEBAJA — un usuario de baja sigue siendo el autor de sus hogares, así que se conserva.')),
                ('id_usuario_vivanto', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('creado_en_legacy', models.DateTimeField(blank=True, null=True)),
                ('importado_en', models.DateTimeField(auto_now=True)),
                ('usuario_sicav', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_legacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario del legacy',
                'verbose_name_plural': 'Usuarios del legacy',
                'ordering': ['usu_usuario'],
            },
        ),
    ]
