# Generated by Django 5.2.15 on 2026-08-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacion', '0006_usuariolegacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracterizacionLegacy',
            fields=[
                ('hog_codigo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('usuario_creador', models.CharField(db_index=True, max_length=100)),
                ('usu_idusuario', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(db_index=True, max_length=40)),
                ('creado_en_legacy', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
                ('miembros', models.PositiveIntegerField(default=0)),
                ('respuestas_definitivas', models.PositiveIntegerField(default=0)),
                ('respuestas_trabajo', models.PositiveIntegerField(default=0)),
                ('capitulos', models.PositiveIntegerField(default=0)),
                ('veredicto', models.CharField(blank=True, db_index=True, max_length=32)),
                ('visible_en_reportes', models.BooleanField(db_index=True, default=False)),
                ('sincronizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_legacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caracterizaciones', to='sincronizacion.usuariolegacy')),
            ],
            options={
                'verbose_name': 'Caracterización del legacy',
                'verbose_name_plural': 'Caracterizaciones del legacy',
                'ordering': ['-creado_en_legacy'],
                'indexes': [models.Index(fields=['usuario_creador', '-creado_en_legacy'], name='sincronizac_usuario_41d82a_idx')],
            },
        ),
    ]
