# Generated by Django 5.2 on 2026-04-09 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(blank=True, db_index=True, max_length=50)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('BUSQUEDA_RNI', 'Búsqueda en el RNI'), ('VER_VICTIMA', 'Vista de datos de víctima'), ('CREAR_HOGAR', 'Creación de hogar'), ('AGREGAR_MIEMBRO', 'Miembro agregado al hogar'), ('RESPONDER_PREGUNTA', 'Respuesta a pregunta'), ('FINALIZAR_ENCUESTA', 'Encuesta finalizada'), ('EXPORTAR', 'Exportación de datos'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('CAMBIO_USUARIO', 'Modificación de usuario'), ('ACCESO_DENEGADO', 'Acceso denegado')], db_index=True, max_length=30)),
                ('recurso', models.CharField(blank=True, max_length=200)),
                ('recurso_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_origen', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('DENEGADO', 'Acceso denegado'), ('ERROR', 'Error')], db_index=True, max_length=10)),
                ('detalle', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'log de acceso',
                'verbose_name_plural': 'logs de acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
