# Generated by Django 5.2 on 2026-04-09 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logacceso',
            name='usuario',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acceso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logacceso',
            index=models.Index(fields=['codigo_usuario', 'timestamp'], name='auditoria_l_codigo__47d04f_idx'),
        ),
        migrations.AddIndex(
            model_name='logacceso',
            index=models.Index(fields=['accion', 'timestamp'], name='auditoria_l_accion_2ff69c_idx'),
        ),
    ]
