# Generated by Django 5.2.15 on 2026-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_logacceso_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacceso',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('BUSQUEDA_RNI', 'Búsqueda en el RNI'), ('VER_VICTIMA', 'Vista de datos de víctima'), ('CREAR_HOGAR', 'Creación de hogar'), ('AGREGAR_MIEMBRO', 'Miembro agregado al hogar'), ('SUBIR_CONSTANCIA', 'Constancia de tutor/cuidador subida'), ('RESPONDER_PREGUNTA', 'Respuesta a pregunta'), ('FINALIZAR_ENCUESTA', 'Encuesta finalizada'), ('EXPORTAR', 'Exportación de datos'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('CAMBIO_USUARIO', 'Modificación de usuario'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('LLAMADA_GEMINI', 'Llamada al asistente IA Gemini'), ('CONSENTIMIENTO_IA', 'Consentimiento de uso de IA'), ('DESCARGA_APK', 'Descarga de APK móvil'), ('CONSULTA_FUENTE_EXTERNA', 'Consulta en fuente externa (RNI/Registraduría)'), ('REGISTRAR_VICTIMA_FUENTE_EXTERNA', 'Registro de víctima desde fuente externa'), ('CAMBIAR_AUTORIZADO', 'Cambio de autorizado del hogar'), ('HABILITAR', 'Verificación de habilitación'), ('PRECARGA_OFFLINE', 'Precarga de datos para trabajo offline')], db_index=True, max_length=50),
        ),
    ]
