# Generated by Django 5.2 on 2026-04-16 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='formulario.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['pregunta__orden'],
            },
        ),
        migrations.CreateModel(
            name='SesionEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('SUSPENDIDA', 'Suspendida — sin finalizar')], db_index=True, default='INICIADA', max_length=15)),
                ('porcentaje_completado', models.PositiveSmallIntegerField(default=0, help_text='0–100. Se recalcula al guardar respuestas.')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encuestador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_encuesta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Encuesta',
                'verbose_name_plural': 'Sesiones de Encuesta',
                'ordering': ['-created_at'],
            },
        ),
    ]
