# Generated by Django 5.2 on 2026-04-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuestas', '0001_initial'),
        ('formulario', '0001_initial'),
        ('hogares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionencuesta',
            name='hogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='hogares.hogar'),
        ),
        migrations.AddField(
            model_name='sesionencuesta',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='formulario.instrumento'),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.sesionencuesta'),
        ),
        migrations.AddIndex(
            model_name='sesionencuesta',
            index=models.Index(fields=['hogar', 'estado'], name='encuestas_s_hogar_i_b3d567_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionencuesta',
            index=models.Index(fields=['encuestador', 'estado'], name='encuestas_s_encuest_252397_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together={('sesion', 'pregunta')},
        ),
    ]
