# Generated by Django 5.2 on 2026-05-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionencuesta',
            name='ruta_entrevista',
            field=models.CharField(choices=[('GENERAL', 'General — caracterización ordinaria'), ('ACCIONES_CONSTITUCIONALES', 'Acciones constitucionales'), ('MODIFICACION_NUCLEO', 'Modificación de núcleo familiar'), ('ESPECIAL', 'Ruta especial — población diferencial')], db_index=True, default='GENERAL', help_text='Ruta de entrevista — independiente del instrumento (Manual UARIV §4).', max_length=30),
        ),
    ]
