# Generated by Django 5.2 on 2026-05-20 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_sesionencuesta_ruta_entrevista'),
        ('formulario', '0003_alter_instrumentoversion_unique_together_and_more'),
        ('hogares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionencuesta',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='formulario.instrumento'),
        ),
        migrations.AddIndex(
            model_name='sesionencuesta',
            index=models.Index(fields=['instrumento', 'ruta_entrevista'], name='encuestas_s_instrum_d0c362_idx'),
        ),
    ]
