# Generated by Django 5.2 on 2026-05-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_alter_sesionencuesta_instrumento_and_more'),
        ('parametricas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionencuesta',
            name='departamento_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_atencion', to='parametricas.departamento'),
        ),
        migrations.AddField(
            model_name='sesionencuesta',
            name='direccion_territorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='parametricas.direccionterritorial'),
        ),
        migrations.AddField(
            model_name='sesionencuesta',
            name='municipio_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_atencion', to='parametricas.municipio'),
        ),
        migrations.AddField(
            model_name='sesionencuesta',
            name='punto_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='parametricas.puntoatencion'),
        ),
    ]
