# Generated by Django 5.2 on 2026-05-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_sesionencuesta_departamento_atencion_and_more'),
        ('formulario', '0004_delete_instrumentoversion'),
        ('hogares', '0004_remove_miembrohogar_hogares_mie_hogar_i_53eb30_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaencuesta',
            options={'ordering': ['pregunta__orden', 'miembro_id'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='miembro',
            field=models.ForeignKey(blank=True, help_text='Miembro del hogar al que aplica la respuesta. NULL si la pregunta es HOGAR.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='hogares.miembrohogar'),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(fields=('sesion', 'pregunta', 'miembro'), name='respuesta_unica_por_miembro'),
        ),
    ]
