# Generated by Django 5.2.15 on 2026-08-04 20:50

import apps.encuestas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_alter_respuestaencuesta_options_and_more'),
        ('victimas', '0012_hechovictima_id_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionVigencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta', models.CharField(choices=[('GENERAL', 'General — caracterización ordinaria'), ('ACCIONES_CONSTITUCIONALES', 'Acciones constitucionales'), ('MODIFICACION_NUCLEO', 'Modificación de núcleo familiar'), ('ESPECIAL', 'Ruta especial — población diferencial')], help_text='Ruta por la que se omitió la vigencia.', max_length=30)),
                ('fecha_ult_caracterizacion', models.DateField(blank=True, help_text='Fecha de la caracterización que estaba vigente.', null=True)),
                ('vigente_hasta', models.DateField(blank=True, help_text='Hasta cuándo estaba vigente esa ficha.', null=True)),
                ('soporte', models.FileField(blank=True, help_text='Foto del fallo, la tutela o el auto que acredita la excepción.', null=True, upload_to=apps.encuestas.models.ruta_soporte_excepcion)),
                ('soporte_nombre', models.CharField(blank=True, help_text='Nombre original del archivo (para mostrar al usuario).', max_length=255)),
                ('observacion', models.TextField(blank=True, help_text='Número de radicado del fallo, o lo que el encuestador anote.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorizada_por', models.ForeignKey(help_text='Quién usó la ruta de excepción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excepciones_vigencia', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_vigencia', to='encuestas.sesionencuesta')),
                ('victima', models.ForeignKey(help_text='La persona que tenía ficha vigente.', on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_vigencia', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Excepción de vigencia',
                'verbose_name_plural': 'Excepciones de vigencia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['victima', 'created_at'], name='encuestas_e_victima_be146f_idx'), models.Index(fields=['ruta'], name='encuestas_e_ruta_4c8104_idx')],
            },
        ),
    ]
