# Generated by Django 5.2.15 on 2026-08-14 16:31

import apps.encuestas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_excepcionvigencia'),
        ('victimas', '0021_limpiar_estado_ruv_no_verificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excepcionvigencia',
            name='anulada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excepciones_vigencia_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='estado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente — la persona puede caracterizarse'), ('USADA', 'Usada — ya se caracterizó con ella'), ('ANULADA', 'Anulada — se dejó sin efecto')], db_index=True, default='VIGENTE', help_text='Una habilitación se consume al usarse.', max_length=10),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='radicado',
            field=models.CharField(blank=True, help_text='Número de radicado del fallo, auto o solicitud que sustenta la excepción.', max_length=100),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='usada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excepcionvigencia',
            name='usada_en_sesion',
            field=models.ForeignKey(blank=True, help_text='La sesión de encuesta que consumió esta habilitación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitacion_consumida', to='encuestas.sesionencuesta'),
        ),
        migrations.AlterField(
            model_name='excepcionvigencia',
            name='autorizada_por',
            field=models.ForeignKey(help_text='Quién autorizó la excepción desde el front. Nunca el encuestador que la ejecuta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excepciones_vigencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excepcionvigencia',
            name='observacion',
            field=models.TextField(blank=True, help_text='Motivo de la excepción, escrito por quien la autoriza.'),
        ),
        migrations.AlterField(
            model_name='excepcionvigencia',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Obsoleto — histórico de las excepciones registradas desde el celular antes del 14-ago-2026. Las nuevas nacen sin sesión.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_vigencia', to='encuestas.sesionencuesta'),
        ),
        migrations.AlterField(
            model_name='excepcionvigencia',
            name='soporte',
            field=models.FileField(blank=True, help_text='Opcional — el documento que acredita la excepción, cargado desde el front. Ya no se captura en campo.', null=True, upload_to=apps.encuestas.models.ruta_soporte_excepcion),
        ),
        migrations.AddIndex(
            model_name='excepcionvigencia',
            index=models.Index(fields=['victima', 'estado'], name='exc_vig_victima_estado_idx'),
        ),
    ]
