# Generated by Django 5.2.15 on 2026-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_recaracterizacionvigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionencuesta',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('SUSPENDIDA', 'Pausada — sin finalizar')], db_index=True, default='INICIADA', max_length=15),
        ),
    ]
