# Generated by Django 5.2 on 2026-04-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentimientoia',
            new_name='ia_consenti_sesion__22126f_idx',
            old_name='ia_consent_sesion_acepto_idx',
        ),
        migrations.RenameIndex(
            model_name='consentimientoia',
            new_name='ia_consenti_encuest_511121_idx',
            old_name='ia_consent_encuestador_idx',
        ),
    ]
