# Generated by Django 5.2 on 2026-04-09 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100)),
                ('puede_buscar_rni', models.BooleanField(default=True, help_text='Buscar víctimas en el Registro Nacional de Información', verbose_name='puede buscar en el RNI')),
                ('puede_caracterizar', models.BooleanField(default=True, help_text='Diligenciar encuestas de caracterización', verbose_name='puede caracterizar')),
                ('puede_ver_reportes', models.BooleanField(default=False, help_text='Acceder al módulo de reportes de producción', verbose_name='puede ver reportes')),
                ('puede_administrar', models.BooleanField(default=False, help_text='CRUD de usuarios, instrumentos y paramétricas', verbose_name='puede administrar')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(help_text='Identificador único de login (equivale a IDUSUARIO del APK)', max_length=50, unique=True, verbose_name='código de usuario')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_admin', models.BooleanField(default=False, help_text='Acceso al panel /admin/ de Django', verbose_name='es administrador')),
                ('fecha_ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='autenticacion.perfil')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'auth_usuario',
            },
        ),
    ]
