# Generated by Django 5.2.15 on 2026-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puede_autorizar_excepciones',
            field=models.BooleanField(default=False, help_text='Habilitar desde el front la actualización de una caracterización vigente por una ruta que omite la regla de los dos años (Manual §5.1.1). No lo tiene el encuestador: quien autoriza no es quien ejecuta.', verbose_name='puede autorizar excepciones de vigencia'),
        ),
    ]
