# Generated by Django 5.2.15 on 2026-09-18 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_activar_autorizar_excepciones'),
        ('parametricas', '0003_alter_puntoatencion_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion_territorial', models.ForeignKey(blank=True, help_text='Área del equipo. Vacío = sin área asignada todavía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='parametricas.direccionterritorial')),
                ('supervisor', models.ForeignKey(help_text='Quien responde por el equipo.', on_delete=django.db.models.deletion.PROTECT, related_name='equipos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'db_table': 'auth_equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desde', models.DateField(auto_now_add=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_equipo_hechas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenencias', to='autenticacion.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenencias_equipo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'miembro de equipo',
                'verbose_name_plural': 'miembros de equipo',
                'db_table': 'auth_equipo_miembro',
                'ordering': ['-desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('hasta__isnull', True)), fields=('usuario',), name='un_equipo_activo_por_usuario')],
            },
        ),
    ]
