# Generated by Django 5.2 on 2026-04-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(db_index=True, max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('aplica_nacionales', models.BooleanField(default=True)),
                ('aplica_extranjeros', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DireccionTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('departamentos', models.ManyToManyField(related_name='direcciones_territoriales', to='parametricas.departamento')),
            ],
            options={
                'verbose_name': 'Dirección Territorial',
                'verbose_name_plural': 'Direcciones Territoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(db_index=True, max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='parametricas.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComunidadNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunidades_negras', to='parametricas.municipio')),
            ],
            options={
                'verbose_name': 'Comunidad Negra',
                'verbose_name_plural': 'Comunidades Negras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion_fisica', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('direccion_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_atencion', to='parametricas.direccionterritorial')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_atencion', to='parametricas.municipio')),
            ],
            options={
                'verbose_name': 'Punto de Atención',
                'verbose_name_plural': 'Puntos de Atención',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResguardoIndigena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('pueblo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resguardos', to='parametricas.municipio')),
            ],
            options={
                'verbose_name': 'Resguardo Indígena',
                'verbose_name_plural': 'Resguardos Indígenas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(db_index=True, max_length=13)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veredas', to='parametricas.municipio')),
            ],
            options={
                'verbose_name': 'Vereda',
                'verbose_name_plural': 'Veredas',
                'ordering': ['municipio__nombre', 'nombre'],
                'unique_together': {('codigo_dane', 'municipio')},
            },
        ),
    ]
