# Generated by Django 5.2.15 on 2026-09-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0003_alter_puntoatencion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidadnegra',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunidades_negras', to='parametricas.municipio'),
        ),
        migrations.AlterField(
            model_name='resguardoindigena',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resguardos', to='parametricas.municipio'),
        ),
    ]
